M10N = {
    48637: {
        "damage_category": "auto",
        "is_tank_damage": True,
        "ability_name": "Attack",
        "description": "Auto",
    },
    48638: {
        "damage_category": "auto",
        "is_tank_damage": True,
        "ability_name": "Attack",
        "description": "Auto",
    },
    46465: {
        "damage_category": "tankbuser",
        "is_tank_damage": True,
        "ability_name": "Deep Impact",
        "description": "Tankbuster",
    },
    46471: {
        "damage_category": "individual",
        "is_tank_damage": False,
        "ability_name": "Alley-oop inferno",
        "description": "Spread puddles",
    },
    46479: {
        "damage_category": "individual",
        "is_tank_damage": False,
        "ability_name": "Cutback Blaze",
        "description": "Targeted fire cone",
    },
    46466: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Divers' Dare",
        "description": "Raidwide",
    },
    46481: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Sick Swell",
        "description": "Deep blue pushy wave",
    },
    46488: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Deep varial",
        "description": "Edge conal",
    },
    46555: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Xtreme spectacular",
        "description": "Proximity ult",
    },
    47049: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Xtreme spectacular",
        "description": "Multi hit ult",
    },
    46499: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Xtreme spectacular",
        "description": "Multi hit ult",
    },
    46476: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Hot Aerial",
        "description": "Tower soak damage",
    },
    46473: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Pyrotation",
        "description": "Party stack fire puddle drop",
    },
    46462: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Firesnaking",
        "description": "Firewall type raidwide",
    },
    46463: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Watersnaking",
        "description": "Firewall type raidwide",
    },
    46505: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Plunging Snap",
        "description": "Baited water cone",
    },
    46506: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Plunging Snap",
        "description": "Baited fire cone",
    },
}
