M10N = {
    48637: {
        "damage_category": "auto",
        "is_tank_damage": True,
        "ability_name": "Attack",
        "description": "Auto",
    },
    48638: {
        "damage_category": "auto",
        "is_tank_damage": True,
        "ability_name": "Attack",
        "description": "Auto",
    },
    48639: {
        "damage_category": "auto",
        "is_tank_damage": True,
        "ability_name": "Attack",
        "description": "Auto",
    },
    48640: {
        "damage_category": "auto",
        "is_tank_damage": True,
        "ability_name": "Attack",
        "description": "Auto",
    },
    44486: {
        "damage_category": "tankbuser",
        "is_tank_damage": True,
        "ability_name": "Deep Impact",
        "description": "Tankbuster",
    },
    46465: {
        "damage_category": "tankbuser",
        "is_tank_damage": True,
        "ability_name": "Deep Impact",
        "description": "Tankbuster",
    },
    46471: {
        "damage_category": "individual",
        "is_tank_damage": False,
        "ability_name": "Alley-oop inferno",
        "description": "Spread puddles",
    },
    46529: {
        "damage_category": "individual",
        "is_tank_damage": False,
        "ability_name": "Alley-oop inferno",
        "description": "Spread puddles",
    },
    46479: {
        "damage_category": "individual",
        "is_tank_damage": False,
        "ability_name": "Cutback Blaze",
        "description": "Targeted fire cone",
    },
    46538: {
        "damage_category": "individual",
        "is_tank_damage": False,
        "ability_name": "Cutback Blaze",
        "description": "Targeted fire cone",
    },
    46466: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Divers' Dare",
        "description": "Raidwide",
    },
    46520: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Divers' Dare",
        "description": "Raidwide",
    },
    46521: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Divers' Dare",
        "description": "Raidwide",
    },
    46481: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Sick Swell",
        "description": "Deep blue pushy wave",
    },
    46540: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Sick Swell",
        "description": "Deep blue pushy wave",
    },
    46488: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Deep varial",
        "description": "Edge conal",
    },
    46555: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Xtreme spectacular",
        "description": "Proximity ult",
    },
    47049: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Xtreme spectacular",
        "description": "Multi hit ult",
    },
    46499: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Xtreme spectacular",
        "description": "Multi hit ult",
    },
    46500: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Xtreme spectacular",
        "description": "Multi hit ult",
    },
    46556: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Xtreme spectacular",
        "description": "Proximity ult",
    },
    47050: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Xtreme spectacular",
        "description": "Multi hit ult",
    },
    46476: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Hot Aerial",
        "description": "Tower soak damage",
    },
    47390: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Hot Aerial",
        "description": "Tower soak damage",
    },
    47391: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Hot Aerial",
        "description": "Tower soak damage",
    },
    47392: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Hot Aerial",
        "description": "Tower soak damage",
    },
    47393: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Hot Aerial",
        "description": "Tower soak damage",
    },
    46473: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Pyrotation",
        "description": "Party stack fire puddle drop",
    },
    46531: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Pyrotation",
        "description": "Party stack fire puddle drop",
    },
    46462: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Firesnaking",
        "description": "Firewall type raidwide",
    },
    46463: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Watersnaking",
        "description": "Firewall type raidwide",
    },
    46505: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Plunging Snap",
        "description": "Baited water cone",
    },
    46506: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Plunging Snap",
        "description": "Baited fire cone",
    },
    44487: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Scathing Steam",
        "description": "Fire + jail",
    },
    46464: {
        "damage_category": "tankbuster",
        "is_tank_damage": True,
        "ability_name": "Hot Impact",
        "description": "Tank buster",
    },
    46518: {
        "damage_category": "tankbuster",
        "is_tank_damage": True,
        "ability_name": "Hot Impact",
        "description": "Tank buster",
    },
    46487: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Freaky Pyrotation",
        "description": "Pair stack (flame bacon phase)",
    },
    46523: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Flame Floater",
        "description": "Limit Cut line",
    },
    46524: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Flame Floater",
        "description": "Limit Cut line",
    },
    46525: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Flame Floater",
        "description": "Limit Cut line",
    },
    46526: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Flame Floater",
        "description": "Limit Cut line",
    },
    46543: {
        "damage_category": "individual",
        "is_tank_damage": False,
        "ability_name": "Awesome Splash",
        "description": "Deep blue spread",
    },
    46544: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Awesome Slab",
        "description": "Deep blue LP",
    },
    46552: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Awesome Slab",
        "description": "Deep blue LP",
    },
    46545: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Xtreme Wave",
        "description": "Stretchy line tether",
    },
    46546: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Xtreme Wave",
        "description": "Stretchy line tether",
    },
    46564: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Deep Aerial",
        "description": "Raidwide jail transition",
    },
    46587: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Steam Burst",
        "description": "Fire + jail",
    },
    45953: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Proteans/Spreads/Unknown",
        "description": "Proteans/spreads/unknown",
    },
    45954: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Proteans/Spreads/Unknown",
        "description": "Proteans/spreads/unknown",
    },
    46510: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Proteans/Spreads/Unknown",
        "description": "Proteans/spreads/unknown",
    },
    46511: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Proteans/Spreads/Unknown",
        "description": "Proteans/spreads/unknown",
    },
    46512: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Proteans/Spreads/Unknown",
        "description": "Proteans/spreads/unknown",
    },
    46513: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Proteans/Spreads/Unknown",
        "description": "Proteans/spreads/unknown",
    },
    46558: {
        "damage_category": "individual",
        "is_tank_damage": False,
        "ability_name": "Proteans/Spreads/Unknown",
        "description": "Proteans/spreads/unknown",
    },
    46561: {
        "damage_category": "individual",
        "is_tank_damage": False,
        "ability_name": "Proteans/Spreads/Unknown",
        "description": "Proteans/spreads/unknown",
    },
    46562: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Proteans/Spreads/Unknown",
        "description": "Proteans/spreads/unknown",
    },
    46577: {
        "damage_category": "individual",
        "is_tank_damage": False,
        "ability_name": "Proteans/Spreads/Unknown",
        "description": "Proteans/spreads/unknown",
    },
    46578: {
        "damage_category": "individual",
        "is_tank_damage": False,
        "ability_name": "Proteans/Spreads/Unknown",
        "description": "Proteans/spreads/unknown",
    },
    46581: {
        "damage_category": "individual",
        "is_tank_damage": False,
        "ability_name": "Proteans/Spreads/Unknown",
        "description": "Proteans/spreads/unknown",
    },
    46582: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Proteans/Spreads/Unknown",
        "description": "Proteans/spreads/unknown",
    },
    46585: {
        "damage_category": "individual",
        "is_tank_damage": True,
        "ability_name": "Proteans/Spreads/Unknown",
        "description": "Proteans/spreads/unknown",
    },
    46586: {
        "damage_category": "individual",
        "is_tank_damage": True,
        "ability_name": "Proteans/Spreads/Unknown",
        "description": "Proteans/spreads/unknown",
    },
}
