M11N = {
    46046: {
        "damage_category": "individual",
        "is_tank_damage": False,
        "ability_name": "Cosmic Kiss",
        "description": "Meteor tower",
    },
    46025: {
        "damage_category": "individual",
        "is_tank_damage": False,
        "ability_name": "Comet",
        "description": "Spread puddle",
    },
    47759: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Flatliner",
        "description": "Knockup",
    },
    46035: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Explosion",
        "description": "Knockup",
    },
    46006: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Crown of Arcadia",
        "description": "Raidwide",
    },
    46005: {
        "damage_category": "auto",
        "is_tank_damage": True,
        "ability_name": "Attack",
        "description": "Auto",
    },
    46061: {
        "damage_category": "Party",
        "is_tank_damage": False,
        "ability_name": "Explosion",
        "description": "Knockup",
    },
    46017: {
        "damage_category": "tankbuster",
        "is_tank_damage": True,
        "ability_name": "Raw Steel",
        "description": "Shared buster",
    },
    46018: {
        "damage_category": "individual",
        "is_tank_damage": False,
        "ability_name": "Impact",
        "description": "Spread puddle",
    },
    47081: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Dance of Domination",
        "description": "Multi hit slashy slash",
    },
    46034: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Dance of Domination",
        "description": "Multi hit slashy slash",
    },
    46080: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Heartbreak Kick",
        "description": "Multi hit tower",
    },
    46060: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Mammoth Meteor",
        "description": "Proximity damage",
    },
    46044: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "One and Only",
        "description": "Raidwide ult",
    },
    46036: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Dance of Domination",
        "description": "Multi hit slashy slash",
    },
    46027: {
        "damage_category": "individual",
        "is_tank_damage": False,
        "ability_name": "Comet",
        "description": "Spread puddle",
    },
    46048: {
        "damage_category": "tankbuster",
        "is_tank_damage": True,
        "ability_name": "Foregone Fatality",
        "description": "Tankbuster tether",
    },
    46054: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Shockwave",
        "description": "LoS meteor",
    },
}
