M9N = {
    45887: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Crowd Kill",
        "description": "Raidwide aether succ",
    },
    45933: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Crowd Kill",
        "description": "Raidwide aether succ",
    },
    45876: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Sadistic Screech",
        "description": "Raidwide / arena transition",
    },
    45926: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Sadistic Screech",
        "description": "Raidwide / arena transition",
    },
    45923: {
        "damage_category": "individual",
        "is_tank_damage": False,
        "ability_name": "Flaying Fry",
        "description": "Puddle spread",
    },
    45890: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Finale Fatale",
        "description": "Raidwide",
    },
    45891: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Finale Fatale",
        "description": "Raidwide",
    },
    45935: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Finale Fatale",
        "description": "Raidwide",
    },
    45936: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Finale Fatale",
        "description": "Raidwide",
    },
    45893: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Insatiable Thirst",
        "description": "Raidwide / arena transition",
    },
    45938: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Insatiable Thirst",
        "description": "Raidwide / arena transition",
    },
    45896: {
        "damage_category": "individual",
        "is_tank_damage": False,
        "ability_name": "Aetherletting",
        "description": "X/+ bait, 2x sets",
    },
    45897: {
        "damage_category": "individual",
        "is_tank_damage": False,
        "ability_name": "Aetherletting",
        "description": "X/+ bait, 2x sets",
    },
    45970: {
        "damage_category": "individual",
        "is_tank_damage": False,
        "ability_name": "Aetherletting",
        "description": "X/+ bait, 2x sets",
    },
    45920: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Brutal Rain",
        "description": "Multi-hit party stack",
    },
    45955: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Brutal Rain",
        "description": "Multi-hit party stack",
    },
    45921: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Killer Voice",
        "description": "Raidwide",
    },
    45956: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Killer Voice",
        "description": "Raidwide",
    },
    45925: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Penetrating Pitch",
        "description": "Light party stacks",
    },
    48038: {
        "damage_category": "auto",
        "is_tank_damage": True,
        "ability_name": "Attack",
        "description": "Auto",
    },
    47047: {
        "damage_category": "auto",
        "is_tank_damage": True,
        "ability_name": "Attack",
        "description": "Auto",
    },
    47048: {
        "damage_category": "auto",
        "is_tank_damage": True,
        "ability_name": "Attack",
        "description": "Auto",
    },
    48039: {
        "damage_category": "auto",
        "is_tank_damage": True,
        "ability_name": "Attack",
        "description": "Auto",
    },
    45915: {
        "damage_category": "tankbuster",
        "is_tank_damage": True,
        "ability_name": "Hardcore",
        "description": "Tank buster",
    },
    45916: {
        "damage_category": "tankbuster",
        "is_tank_damage": True,
        "ability_name": "Hardcore",
        "description": "Tank buster",
    },
    45951: {
        "damage_category": "tankbuster",
        "is_tank_damage": True,
        "ability_name": "Hardcore",
        "description": "Tank buster",
    },
    45952: {
        "damage_category": "tankbuster",
        "is_tank_damage": True,
        "ability_name": "Hardcore",
        "description": "Tank buster",
    },
    45941: {
        "damage_category": "individual",
        "is_tank_damage": False,
        "ability_name": "Blast Beat",
        "description": "Growing ring puddle bait",
    },
    45942: {
        "damage_category": "individual",
        "is_tank_damage": False,
        "ability_name": "Blast Beat",
        "description": "Growing ring puddle bait",
    },
    45963: {
        "damage_category": "tankbuster",
        "is_tank_damage": True,
        "ability_name": "Plummet",
        "description": "Tower buster",
    },
    45974: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Bloody Bondage",
        "description": "Hell in a cell tower",
    },
    45977: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Blood Lash",
        "description": "Hell in a cell dot",
    },
    45978: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Blood Lash",
        "description": "Hell in a cell dot",
    },
    45979: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Blood Lash",
        "description": "Hell in a cell dot",
    },
    45985: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Bloody Bondage",
        "description": "Hell in a cell tower",
    },
    45991: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Sanguine Scratch",
        "description": "TODO",
    },
    45982: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Ultrasonic Spread",
        "description": "Role spread",
    },
    45983: {
        "damage_category": "party",
        "is_tank_damage": False,
        "ability_name": "Ultrasonic Amp",
        "description": "Light party stack",
    },
    47235: {
        "damage_category": "individual",
        "is_tank_damage": True,
        "ability_name": "Ultrasonic Spread",
        "description": "Role spread (tank)",
    },
}
